services:
  # Contenedor Laravel
  api:
    build:
      context: ./backend/laravel-api/
      dockerfile: Dockerfile
    container_name: laravel-api
    user: "${UID}:${GID}"
    volumes:
      - ./backend/laravel-api:/var/www/html:cached
      - /var/www/html/vendor
    depends_on:
      - db
    ports:
      - "8000:8000"   # Exponemos Laravel al host
    networks:
      - task-flow-network

  # Contenedor Vue
  frontend:
    build:
      context: frontend/vue-SPA/
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"  # Exponemos Vite al host
    volumes:
      - ./frontend/vue-SPA:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - task-flow-network

  # Contenedor PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - task-flow-network

volumes:
  pgdata:
    external: false

networks:
  task-flow-network:
    driver: bridge
