
services:
# ----------------------
# Contenedor Laravel
# ----------------------

  api:
    build:
      context: ./backend/laravel-api/
      dockerfile: Dockerfile
    container_name: laravel-api
    user: "${UID}:${GID}"
    volumes:
       - ./backend/laravel-api:/var/www/html:cached
       - /var/www/html/vendor
    depends_on:
      - db
    expose:
      - "8000"          # exponemos solo para la red interna
    networks:
      - task-flow-network

# ----------------------
# Contenedor Vue
# ----------------------
  frontend:
    build:
      context: frontend/vue-SPA/
      dockerfile: Dockerfile
    expose:
      - "5173"          # solo para la red interna
    volumes:
      - ./frontend/vue-SPA:/app        # tu c√≥digo local
      - /app/node_modules              # node_modules dentro del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - task-flow-network

# ----------------------
# Contenedor PostgreSQL
# ----------------------
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - task-flow-network

# ----------------------
# Contenedor Nginx
# ----------------------
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    ports:
      - "80:80" # localhost:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - task-flow-network


volumes:
  pgdata:
    external: false

networks:
  task-flow-network:
    driver: bridge