name: Construir y subir im√°genes Docker (Deploy)

on:
  push:
    branches:
      - deploy
jobs:
  tests-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar test del backend
        run: |
          docker compose -f docker-compose.prod.yml run --rm api php artisan test

  tests-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias del frontend
        run: |
          cd frontend/vue-SPA
          npm install

      - name: Ejecutar test del frontend
        run: |
          cd frontend/vue-SPA
          npm run test --if-present
